version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: asia-southeast1-docker.pkg.dev/efiss-394203/efiss/data-manager-fe:latest
    ports:
      - "3000:3000"
